version: '3'

tasks:
  gen-sso:
    desc: Генерация только sso.proto
    cmds:
      - protoc -I proto proto/sso/sso.proto --go_out=gen/go --go_opt=paths=source_relative --go-grpc_out=gen/go --go-grpc_opt=paths=source_relative

  gen-creator:
    desc: Генерация только creator.proto
    cmds:
      - protoc -I proto proto/creator/creator.proto --go_out=gen/go --go_opt=paths=source_relative --go-grpc_out=gen/go --go-grpc_opt=paths=source_relative

  gen-all:
    desc: Генерация всех proto
    cmds:
      - task: gen-sso
      - task: gen-creator
